services:
  - type: web
    name: Prebid-Dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bot_server:app"
    plan: starter
    autoDeploy: true
